IF DB_ID(N'Loja') IS NULL
	CREATE DATABASE Loja;
ELSE
	USE Loja;
GO

-- Ex01 --
SELECT * FROM CLIENTES;
GO

-- Ex02 --
SELECT * FROM CLIENTES
ORDER BY Nome;
GO

-- Ex03 --
SELECT * FROM CLIENTES
ORDER BY Idade;
GO

-- Ex04 --
SELECT * FROM CLIENTES
ORDER BY Idade DESC;
GO

-- Ex05 --
SELECT * FROM CLIENTES
ORDER BY Sexo DESC;
GO

-- Ex06 --
SELECT Nome, 
	   Idade,
	   Email
FROM CLIENTES
GO

-- Ex07 --
SELECT Nome, 
	   Idade,
	   Email
FROM CLIENTES
ORDER BY Nome;
GO

-- Ex08 --
SELECT ID	  AS 'Codigo do Cliente',
	   Nome, 
	   Idade,
	   Email
FROM CLIENTES
WHERE ID >= 10;
GO

-- Ex09 --
SELECT TOP 5
	   ID	  AS 'Codigo do Cliente',
	   Nome, 
	   Idade,
	   Email
FROM CLIENTES
ORDER BY Nome
GO

-- Ex10 --
SELECT ID	  AS 'Codigo do Cliente',
	   Nome,
	   Sexo,
	   Idade,
	   Email  AS 'E-mail'
FROM CLIENTES
WHERE Idade >= 30 AND
	  Sexo = 'm'
ORDER BY Nome;
GO

---------- Lista03 ----------
-- Ex01 --
ALTER TABLE CLIENTES
    ADD Telefone    CHAR(10)
GO

ALTER TABLE CLIENTES
    ADD DDD    CHAR(2)
GO

-- Ex02 --
UPDATE CLIENTES SET Telefone = '3664-5060', DDD = '12' WHERE ID = 01;
UPDATE CLIENTES SET Telefone = '3664-8090', DDD = '12' WHERE ID = 02;
UPDATE CLIENTES SET Telefone = '3663-1070', DDD = '12' WHERE ID = 03;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 04;
UPDATE CLIENTES SET Telefone = '3664-6070', DDD = '12' WHERE ID = 05;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 06;
UPDATE CLIENTES SET Telefone = '98790-6070',DDD = '12' WHERE ID = 07;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 08;
UPDATE CLIENTES SET Telefone = '97070-6070',DDD = '12' WHERE ID = 09;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 10;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 11;
UPDATE CLIENTES SET Telefone = '99555-0001',DDD = '11' WHERE ID = 12;
UPDATE CLIENTES SET Telefone = '97890-1010',DDD = '11' WHERE ID = 13;
UPDATE CLIENTES SET Telefone = NULL,		DDD = NULL WHERE ID = 14;
UPDATE CLIENTES SET Telefone = '98888-0102',DDD = NULL WHERE ID = 15;
GO

SELECT * FROM CLIENTES
GO

-- Ex03 --
SELECT *
    INTO clientes_COPIA
FROM CLIENTES;
GO

ALTER TABLE clientes_COPIA
ADD CONSTRAINT PK_clientes_COPIA PRIMARY KEY (ID);

Select TABLE_CATALOG     AS 'Banco de Dados',
       TABLE_NAME        AS 'Tabela',
       CONSTRAINT_TYPE   AS 'Tipo de Restrição',
       CONSTRAINT_NAME   AS 'Nome da Restrição'
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'clientes_COPIA';
GO

DROP TABLE clientes_COPIA
GO

-- Ex04 --
SELECT *
	INTO CLIENTES2
FROM CLIENTES
WHERE Telefone IS NOT NULL;
GO

SELECT * FROM CLIENTES2
GO

DROP TABLE CLIENTES2
GO

-- Ex05 --
DELETE FROM CLIENTES2 WHERE DDD = NULL;
GO

-- Ex06 --
TRUNCATE TABLE CLIENTES2;
GO

-- Ex07 --
DROP TABLE CLIENTES2
GO

-- Ex08 --
UPDATE CLIENTES
	SET DDD = '15',
		Email = 'fernando.pereira@uol.com.br'
WHERE ID = 15;
GO

-- Ex09 --
SELECT ID,
	   Nome, 
	   Sexo,
	   Idade,
	   DDD,
	   Telefone
FROM CLIENTES
WHERE Idade > 40
ORDER BY Idade	DESC;
GO

-- Ex10 --
